ci:
  skip: [interrogate]

default_language_version:
  python: python3.10

repos:
  # Formatters
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: fix-encoding-pragma
        args: [--remove]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4 # Use the sha or tag you want to point at
    hooks:
      - id: prettier

  # Notebook tools
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        args:
          - "--drop-empty-cells"
          - "--extra-keys"
          - "metadata.vscode metadata.language_info.version cell.metadata.papermill"

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.1
    hooks:
      - id: nbqa-black
        additional_dependencies: [black==23.1.0]
        args: [--nbqa-mutate]
      - id: nbqa-pyupgrade
        additional_dependencies: [pyupgrade==3.3.1]
        args: [--nbqa-mutate, --py310-plus]
      - id: nbqa-flake8
      - id: nbqa-check-ast
      - id: nbqa-isort
        additional_dependencies: [isort==5.12.0]
        args: [--nbqa-mutate]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        types: [file]
        types_or: [python, pyi, markdown, rst, jupyter]
        args: [-L doas]
