name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  test:
    name: Run ${{ matrix.case_study }}
    runs-on: ubuntu-latest
    needs: [pre-commit]
    strategy:
      matrix:
        case_study: [4TT, dPSI, rc]

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Python "3.10"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r requirements.txt
      - name: Show installed packages
        run: python -m pip freeze
      - name: Run tests
        run: |
          python -m pytest ${{ matrix.case_study }}
